// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"context"

	"github.com/dagger/cloak/sdk/go/dagger"
)

func main() {
	dagger.Serve(context.Background(), map[string]func(context.Context, dagger.ArgsInput) (interface{}, error){})
}
